name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build production binary
        run: ./scripts/buildprod.sh

      # Paso de autenticación modificado (¡clave aquí!)
      - name: Authenticate to GCP
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: omega-monolith-452302-f0
          export_default_credentials: true
          auth: true  # ¡Este parámetro faltaba!

      - name: Build and Push Docker Image
        run: |-
          gcloud builds submit --quiet \
            --tag us-central1-docker.pkg.dev/omega-monolith-452302-f0/notely-ar-repo/notely-app:${{ github.sha }} .